# bank section:
#     establishes basic parameters of bank operation
#     maxMoney : maximum amount a player can have
#     interestDays : days to double the account, 0 for no interest or 1-365
#     maxLoans : total loans a player can have oustanding

bank:
  moneySign: Money Bank
  XPSign: XP Bank
  ATMSign: ATM
  LoanSign: Loans
  currency:
    name: 'Emerald'
    plural: Emeralds
    decimals: 2
    denominations:
    - EMERALD_BLOCK,9
    - EMERALD,1
  maxMoney: 10000000
  interestDays: 180
  maxLoans: 10000
