name: BankMaster
main: com.github.JohnGuru.BankMaster.BankMaster
version: 1.3
description: General manager for bank accounts
author: JohnGuru
commands:
  bank:
    description: Display account balance
    usage: /<command> | /<command> pay <player> <amount>
    permission: bankmaster.use
  audit:
    description: Display account status
    usage: /<command> <player>
    permission: bankmaster.admin
  bankmaster:
    aliases: [banker, bm]
    description: adjust the user's account balance. Clears any outstanding loans
    usage: /<command> [add|rem|set] <player> <amount>
    permission: bankmaster.admin
    
permissions:
  bankmaster.use:
    description: can use bank command
    default: true
  bankmaster.admin:
    description: can use administrator commands
    default: op 